vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.mouse = 'a'
vim.opt.showmode = false
vim.opt.breakindent = true
vim.opt.undofile = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.signcolumn = 'yes'
vim.opt.updatetime = 250
vim.opt.timeoutlen = 300
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.list = true
vim.opt.listchars = { tab = '» ', trail = '·', nbsp = '␣' }
vim.opt.inccommand = 'split'
vim.opt.cursorline = false
vim.opt.scrolloff = 20
vim.opt.guicursor = 'n-v-i-c:block'
vim.opt.clipboard = 'unnamedplus,unnamed'
vim.opt.wildignore = '*node_modules/**'
vim.opt.wrap = false
vim.opt.termguicolors = true
vim.opt.conceallevel = 1
vim.notify = require 'notify'
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.g.terminal_color_0 = '#2a273f' -- black
vim.g.terminal_color_1 = '#eb6f92' -- red
vim.g.terminal_color_2 = '#9ccfd8' -- green
vim.g.terminal_color_3 = '#f6c177' -- yellow
vim.g.terminal_color_4 = '#31748f' -- blue
vim.g.terminal_color_5 = '#c4a7e7' -- magenta
vim.g.terminal_color_6 = '#ebbcba' -- cyan
vim.g.terminal_color_7 = '#e0def4' -- white
